---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - xmonad
        - libghc-xmonad-contrib-dev 
        - libghc-xmonad-dev 
        - suckless-tools
        - xmobar
        - vim
        - ranger

  - name: copy xmonad config files
    copy:
      src: files/xmonad/
      dest: /home/crisber/.config/xmonad/

  - name: copy ranger config files
    copy:
      src: files/ranger/
      dest: /home/crisber/.config/ranger/
