---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - xmonad
        - libghc-xmonad-contrib-dev 
        - libghc-xmonad-dev 
        - suckless-tools
        - xmobar
        - vim
        - ranger

  - name: copy xmonad config files
    copy:
      src: files/xmonad/
      dest: "{{ lookup('env', 'HOME') }}/.config/xmonad/"

  - name: copy ranger config files
    copy:
      src: files/ranger/
      dest: "{{ lookup('env', 'HOME') }}/.config/ranger/"
      mode: preserve

  - name: install neovim lastest stable
    block:
    - name: create nvim dir in opt
      file:
        path: /opt/nvim
        state: directory
        mode: "0755"

    - name: download nvim appimage
      get_url: 
        url: https://github.com/neovim/neovim/releases/download/v0.11.6/nvim-linux-x86_64.appimage
        dest: /opt/nvim/nvim-0.11.6-linux-x86_64.appimage
        mode: "0755"

    - name: symblink to /usr/local/bin 
      file:
        src: /opt/nvim/nvim-0.11.6-linux-x86_64.appimage
        dest: /usr/local/bin/nvim
        state: link
        force: true

    - name: copy nvim config files
      copy:
        src: files/nvim/
        dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
        # owner: "{{ lookup('env', 'USER') }}"
        # group: "{{ lookup('env', 'USER') }}"
        mode: "0644"
        directory_mode: "0755"

  - name: install nerdfonts
    block:
    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        state: directory

    - name: firacode exists
      find: 
        paths: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        patterns: "Jet*Brains*Mono*Nerd*Font"
      register: jetbrains_fonts

    - name: download jet brains mono
      when: jetbrains_fonts.matched == 0
      unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        remote_src: yes

    - name: rebuild font cache
      command: "fc-cache -f"
      changed_when: true


